# Generated by Django 6.0.6 on 2026-06-15 15:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_D', models.PositiveSmallIntegerField(default=0)),
                ('puntuacion_A', models.PositiveSmallIntegerField(default=0)),
                ('puntuacion_S', models.PositiveSmallIntegerField(default=0)),
                ('nivel_D', models.CharField(choices=[('normal', 'Normal'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo'), ('muy_severo', 'Muy severo')], default='normal', max_length=20)),
                ('nivel_A', models.CharField(choices=[('normal', 'Normal'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo'), ('muy_severo', 'Muy severo')], default='normal', max_length=20)),
                ('nivel_S', models.CharField(choices=[('normal', 'Normal'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo'), ('muy_severo', 'Muy severo')], default='normal', max_length=20)),
                ('nivel_global', models.CharField(choices=[('normal', 'Normal'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo'), ('muy_severo', 'Muy severo')], default='normal', max_length=20)),
                ('confianza_global', models.FloatField(default=0.0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('consentimiento_privacidad', models.BooleanField(default=False)),
                ('fecha_consentimiento', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('respiracion', 'Ejercicio de respiración'), ('mindfulness', 'Mindfulness'), ('actividad', 'Actividad física'), ('escritura', 'Escritura / diario'), ('social', 'Contacto social'), ('profesional', 'Derivación a profesional'), ('psicoeducacion', 'Psicoeducación'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('derivar_profesional', models.BooleanField(default=False)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='psicoia.diagnostico')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('tokens_usados', models.PositiveIntegerField(default=0)),
                ('protocolo_crisis_activo', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=10)),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emocion_nlp', models.CharField(choices=[('neutral', 'Neutral'), ('tristeza', 'Tristeza'), ('ansiedad', 'Ansiedad'), ('alegria', 'Alegría'), ('miedo', 'Miedo'), ('enojo', 'Enojo'), ('sorpresa', 'Sorpresa'), ('apatia', 'Apatía')], default='neutral', max_length=20)),
                ('tokens_mensaje', models.PositiveIntegerField(default=0)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='psicoia.sesion')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='psicoia.sesion'),
        ),
        migrations.CreateModel(
            name='AnalisisFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emocion_predominante', models.CharField(choices=[('neutral', 'Neutral'), ('tristeza', 'Tristeza'), ('ansiedad', 'Ansiedad'), ('alegria', 'Alegría'), ('miedo', 'Miedo'), ('enojo', 'Enojo'), ('sorpresa', 'Sorpresa'), ('apatia', 'Apatía')], default='neutral', max_length=20)),
                ('confianza', models.FloatField(default=0.0)),
                ('mensaje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_facial', to='psicoia.mensaje')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_faciales', to='psicoia.sesion')),
            ],
            options={
                'verbose_name': 'Análisis Facial',
                'verbose_name_plural': 'Análisis Faciales',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaDASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveSmallIntegerField()),
                ('respuesta', models.PositiveSmallIntegerField()),
                ('subescala', models.CharField(choices=[('D', 'Depresión'), ('A', 'Ansiedad'), ('S', 'Estrés')], max_length=1)),
                ('mensaje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuesta_dass', to='psicoia.mensaje')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_dass', to='psicoia.sesion')),
            ],
            options={
                'verbose_name': 'Respuesta DASS-21',
                'verbose_name_plural': 'Respuestas DASS-21',
                'unique_together': {('sesion', 'numero_item')},
            },
        ),
    ]
