# Generated by Django 6.0.6 on 2026-06-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='consentimiento_privacidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_consentimiento',
        ),
        migrations.AddField(
            model_name='sesion',
            name='estado_dass',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
